spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ringrecordplayer?serverTimezone=UTC
    username: root
    password: 200208

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB





#自动建表配置
mybatis:
  table:
    auto: update
  model:
    pack: com.wuguozhang.domain
  database:
    type: mysql

mybatis-plus:
  mapper-locations: classpath*:xxxxxx/*.xml,classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml
server:
  port: 8888

